version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend: 
    build: '.'
    container_name: books-backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
